export type Quarterback = {
    // fantasy ranking
    RANK: string
    NAME: string
    CMP: string
    PASS_ATT: string
    PCT: string
    PASS_YDS: string
    YPA: string
    PASS_TD: string
    INT: string
    SACKS: string
    RUSH_ATT: string
    RUSH_YDS: string
    RUSH_TD: string
    FUMBLES: string
    GAMES_PLAYED: string
    FPTS: string
    FPTSPG: string
    ROST: string
}

export const quarterback_stats: Array<Quarterback> = [
    {
        "RANK": "1",
        "NAME": "Patrick Mahomes II (KC)",
        "CMP": "435",
        "PASS_ATT": "648",
        "PCT": "67.1",
        "PASS_YDS": "5,250",
        "YPA": "8.1",
        "PASS_TD": "41",
        "INT": "12",
        "SACKS": "26",
        "RUSH_ATT": "61",
        "RUSH_YDS": "358",
        "RUSH_TD": "4",
        "FUMBLES": "0",
        "GAMES_PLAYED": "17",
        "FPTS": "429.4",
        "FPTSPG": "25.3",
        "ROST": "99.9%"
    },
    {
        "RANK": "2",
        "NAME": "Josh Allen (BUF)",
        "CMP": "362",
        "PASS_ATT": "573",
        "PCT": "63.2",
        "PASS_YDS": "4,316",
        "YPA": "7.5",
        "PASS_TD": "35",
        "INT": "14",
        "SACKS": "33",
        "RUSH_ATT": "126",
        "RUSH_YDS": "776",
        "RUSH_TD": "7",
        "FUMBLES": "5",
        "GAMES_PLAYED": "17",
        "FPTS": "412.4",
        "FPTSPG": "24.3",
        "ROST": "99.9%"
    },
    {
        "RANK": "3",
        "NAME": "Jalen Hurts (PHI)",
        "CMP": "306",
        "PASS_ATT": "460",
        "PCT": "66.5",
        "PASS_YDS": "3,701",
        "YPA": "8.0",
        "PASS_TD": "22",
        "INT": "6",
        "SACKS": "38",
        "RUSH_ATT": "165",
        "RUSH_YDS": "760",
        "RUSH_TD": "13",
        "FUMBLES": "2",
        "GAMES_PLAYED": "15",
        "FPTS": "384.1",
        "FPTSPG": "25.6",
        "ROST": "99.9%"
    },
    {
        "RANK": "4",
        "NAME": "Joe Burrow (CIN)",
        "CMP": "418",
        "PASS_ATT": "610",
        "PCT": "68.5",
        "PASS_YDS": "4,527",
        "YPA": "7.4",
        "PASS_TD": "36",
        "INT": "12",
        "SACKS": "41",
        "RUSH_ATT": "76",
        "RUSH_YDS": "259",
        "RUSH_TD": "5",
        "FUMBLES": "3",
        "GAMES_PLAYED": "17",
        "FPTS": "369.0",
        "FPTSPG": "21.7",
        "ROST": "99.8%"
    },
    {
        "RANK": "5",
        "NAME": "Geno Smith (SEA)",
        "CMP": "399",
        "PASS_ATT": "572",
        "PCT": "69.8",
        "PASS_YDS": "4,282",
        "YPA": "7.5",
        "PASS_TD": "30",
        "INT": "11",
        "SACKS": "46",
        "RUSH_ATT": "68",
        "RUSH_YDS": "366",
        "RUSH_TD": "1",
        "FUMBLES": "4",
        "GAMES_PLAYED": "17",
        "FPTS": "314.9",
        "FPTSPG": "18.5",
        "ROST": "90.6%"
    },
    {
        "RANK": "6",
        "NAME": "Justin Fields (CHI)",
        "CMP": "192",
        "PASS_ATT": "318",
        "PCT": "60.4",
        "PASS_YDS": "2,242",
        "YPA": "7.1",
        "PASS_TD": "17",
        "INT": "11",
        "SACKS": "55",
        "RUSH_ATT": "160",
        "RUSH_YDS": "1,143",
        "RUSH_TD": "8",
        "FUMBLES": "2",
        "GAMES_PLAYED": "15",
        "FPTS": "307.0",
        "FPTSPG": "20.5",
        "ROST": "97.5%"
    },
    {
        "RANK": "7",
        "NAME": "Kirk Cousins (MIN)",
        "CMP": "424",
        "PASS_ATT": "643",
        "PCT": "65.9",
        "PASS_YDS": "4,547",
        "YPA": "7.1",
        "PASS_TD": "29",
        "INT": "14",
        "SACKS": "46",
        "RUSH_ATT": "31",
        "RUSH_YDS": "97",
        "RUSH_TD": "2",
        "FUMBLES": "3",
        "GAMES_PLAYED": "17",
        "FPTS": "305.6",
        "FPTSPG": "18.0",
        "ROST": "91.9%"
    },
    {
        "RANK": "8",
        "NAME": "Trevor Lawrence (JAC)",
        "CMP": "387",
        "PASS_ATT": "584",
        "PCT": "66.3",
        "PASS_YDS": "4,113",
        "YPA": "7.0",
        "PASS_TD": "25",
        "INT": "8",
        "SACKS": "27",
        "RUSH_ATT": "62",
        "RUSH_YDS": "291",
        "RUSH_TD": "5",
        "FUMBLES": "9",
        "GAMES_PLAYED": "17",
        "FPTS": "303.7",
        "FPTSPG": "17.9",
        "ROST": "95.7%"
    },
    {
        "RANK": "9",
        "NAME": "Daniel Jones (NYG)",
        "CMP": "317",
        "PASS_ATT": "472",
        "PCT": "67.2",
        "PASS_YDS": "3,205",
        "YPA": "6.8",
        "PASS_TD": "15",
        "INT": "5",
        "SACKS": "44",
        "RUSH_ATT": "120",
        "RUSH_YDS": "708",
        "RUSH_TD": "7",
        "FUMBLES": "3",
        "GAMES_PLAYED": "16",
        "FPTS": "293.9",
        "FPTSPG": "18.4",
        "ROST": "92.1%"
    },
    {
        "RANK": "10",
        "NAME": "Jared Goff (DET)",
        "CMP": "382",
        "PASS_ATT": "587",
        "PCT": "65.1",
        "PASS_YDS": "4,438",
        "YPA": "7.6",
        "PASS_TD": "29",
        "INT": "7",
        "SACKS": "23",
        "RUSH_ATT": "29",
        "RUSH_YDS": "73",
        "RUSH_TD": "0",
        "FUMBLES": "4",
        "GAMES_PLAYED": "17",
        "FPTS": "291.3",
        "FPTSPG": "17.1",
        "ROST": "72.6%"
    },
    {
        "RANK": "11",
        "NAME": "Justin Herbert (LAC)",
        "CMP": "477",
        "PASS_ATT": "699",
        "PCT": "68.2",
        "PASS_YDS": "4,739",
        "YPA": "6.8",
        "PASS_TD": "25",
        "INT": "10",
        "SACKS": "38",
        "RUSH_ATT": "54",
        "RUSH_YDS": "147",
        "RUSH_TD": "0",
        "FUMBLES": "3",
        "GAMES_PLAYED": "17",
        "FPTS": "291.3",
        "FPTSPG": "17.1",
        "ROST": "96.8%"
    },
    {
        "RANK": "12",
        "NAME": "Tom Brady (FA)",
        "CMP": "490",
        "PASS_ATT": "733",
        "PCT": "66.8",
        "PASS_YDS": "4,694",
        "YPA": "6.4",
        "PASS_TD": "25",
        "INT": "9",
        "SACKS": "22",
        "RUSH_ATT": "29",
        "RUSH_YDS": "-1",
        "RUSH_TD": "1",
        "FUMBLES": "4",
        "GAMES_PLAYED": "17",
        "FPTS": "280.5",
        "FPTSPG": "16.5",
        "ROST": "1.3%"
    },
    {
        "RANK": "13",
        "NAME": "Aaron Rodgers (NYJ)",
        "CMP": "350",
        "PASS_ATT": "542",
        "PCT": "64.6",
        "PASS_YDS": "3,695",
        "YPA": "6.8",
        "PASS_TD": "26",
        "INT": "12",
        "SACKS": "32",
        "RUSH_ATT": "34",
        "RUSH_YDS": "94",
        "RUSH_TD": "1",
        "FUMBLES": "4",
        "GAMES_PLAYED": "17",
        "FPTS": "251.3",
        "FPTSPG": "14.8",
        "ROST": "93.6%"
    },
    {
        "RANK": "14",
        "NAME": "Lamar Jackson (BAL)",
        "CMP": "203",
        "PASS_ATT": "326",
        "PCT": "62.3",
        "PASS_YDS": "2,242",
        "YPA": "6.9",
        "PASS_TD": "17",
        "INT": "7",
        "SACKS": "26",
        "RUSH_ATT": "112",
        "RUSH_YDS": "764",
        "RUSH_TD": "3",
        "FUMBLES": "2",
        "GAMES_PLAYED": "12",
        "FPTS": "243.1",
        "FPTSPG": "20.3",
        "ROST": "99.4%"
    },
    {
        "RANK": "15",
        "NAME": "Tua Tagovailoa (MIA)",
        "CMP": "259",
        "PASS_ATT": "400",
        "PCT": "64.8",
        "PASS_YDS": "3,548",
        "YPA": "8.9",
        "PASS_TD": "25",
        "INT": "8",
        "SACKS": "21",
        "RUSH_ATT": "24",
        "RUSH_YDS": "70",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "13",
        "FPTS": "239.0",
        "FPTSPG": "18.4",
        "ROST": "92.0%"
    },
    {
        "RANK": "16",
        "NAME": "Russell Wilson (DEN)",
        "CMP": "292",
        "PASS_ATT": "483",
        "PCT": "60.5",
        "PASS_YDS": "3,524",
        "YPA": "7.3",
        "PASS_TD": "16",
        "INT": "11",
        "SACKS": "55",
        "RUSH_ATT": "55",
        "RUSH_YDS": "277",
        "RUSH_TD": "3",
        "FUMBLES": "2",
        "GAMES_PLAYED": "15",
        "FPTS": "237.0",
        "FPTSPG": "15.8",
        "ROST": "84.4%"
    },
    {
        "RANK": "17",
        "NAME": "Derek Carr (NO)",
        "CMP": "305",
        "PASS_ATT": "502",
        "PCT": "60.8",
        "PASS_YDS": "3,522",
        "YPA": "7.0",
        "PASS_TD": "24",
        "INT": "14",
        "SACKS": "27",
        "RUSH_ATT": "24",
        "RUSH_YDS": "102",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "15",
        "FPTS": "233.0",
        "FPTSPG": "15.5",
        "ROST": "57.9%"
    },
    {
        "RANK": "18",
        "NAME": "Dak Prescott (DAL)",
        "CMP": "261",
        "PASS_ATT": "394",
        "PCT": "66.2",
        "PASS_YDS": "2,860",
        "YPA": "7.3",
        "PASS_TD": "23",
        "INT": "15",
        "SACKS": "20",
        "RUSH_ATT": "45",
        "RUSH_YDS": "182",
        "RUSH_TD": "1",
        "FUMBLES": "1",
        "GAMES_PLAYED": "12",
        "FPTS": "213.6",
        "FPTSPG": "17.8",
        "ROST": "93.9%"
    },
    {
        "RANK": "19",
        "NAME": "Kyler Murray (ARI)",
        "CMP": "259",
        "PASS_ATT": "390",
        "PCT": "66.4",
        "PASS_YDS": "2,368",
        "YPA": "6.1",
        "PASS_TD": "14",
        "INT": "7",
        "SACKS": "25",
        "RUSH_ATT": "67",
        "RUSH_YDS": "418",
        "RUSH_TD": "3",
        "FUMBLES": "2",
        "GAMES_PLAYED": "11",
        "FPTS": "207.6",
        "FPTSPG": "18.9",
        "ROST": "68.3%"
    },
    {
        "RANK": "20",
        "NAME": "Marcus Mariota (PHI)",
        "CMP": "184",
        "PASS_ATT": "300",
        "PCT": "61.3",
        "PASS_YDS": "2,219",
        "YPA": "7.4",
        "PASS_TD": "15",
        "INT": "9",
        "SACKS": "28",
        "RUSH_ATT": "85",
        "RUSH_YDS": "438",
        "RUSH_TD": "4",
        "FUMBLES": "3",
        "GAMES_PLAYED": "13",
        "FPTS": "205.7",
        "FPTSPG": "15.8",
        "ROST": "0.6%"
    },
    {
        "RANK": "21",
        "NAME": "Davis Mills (HOU)",
        "CMP": "292",
        "PASS_ATT": "479",
        "PCT": "61.0",
        "PASS_YDS": "3,118",
        "YPA": "6.5",
        "PASS_TD": "17",
        "INT": "15",
        "SACKS": "31",
        "RUSH_ATT": "32",
        "RUSH_YDS": "108",
        "RUSH_TD": "2",
        "FUMBLES": "3",
        "GAMES_PLAYED": "15",
        "FPTS": "196.6",
        "FPTSPG": "13.1",
        "ROST": "0.6%"
    },
    {
        "RANK": "22",
        "NAME": "Andy Dalton (CAR)",
        "CMP": "252",
        "PASS_ATT": "378",
        "PCT": "66.7",
        "PASS_YDS": "2,871",
        "YPA": "7.6",
        "PASS_TD": "18",
        "INT": "9",
        "SACKS": "25",
        "RUSH_ATT": "30",
        "RUSH_YDS": "54",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "14",
        "FPTS": "183.3",
        "FPTSPG": "13.1",
        "ROST": "0.7%"
    },
    {
        "RANK": "23",
        "NAME": "Mac Jones (NE)",
        "CMP": "288",
        "PASS_ATT": "442",
        "PCT": "65.2",
        "PASS_YDS": "2,997",
        "YPA": "6.8",
        "PASS_TD": "14",
        "INT": "11",
        "SACKS": "34",
        "RUSH_ATT": "47",
        "RUSH_YDS": "102",
        "RUSH_TD": "1",
        "FUMBLES": "1",
        "GAMES_PLAYED": "14",
        "FPTS": "181.1",
        "FPTSPG": "12.9",
        "ROST": "6.3%"
    },
    {
        "RANK": "24",
        "NAME": "Jacoby Brissett (WAS)",
        "CMP": "236",
        "PASS_ATT": "369",
        "PCT": "64.0",
        "PASS_YDS": "2,608",
        "YPA": "7.1",
        "PASS_TD": "12",
        "INT": "6",
        "SACKS": "24",
        "RUSH_ATT": "49",
        "RUSH_YDS": "243",
        "RUSH_TD": "2",
        "FUMBLES": "4",
        "GAMES_PLAYED": "14",
        "FPTS": "174.7",
        "FPTSPG": "12.5",
        "ROST": "1.0%"
    },
    {
        "RANK": "25",
        "NAME": "Jimmy Garoppolo (LV)",
        "CMP": "207",
        "PASS_ATT": "308",
        "PCT": "67.2",
        "PASS_YDS": "2,437",
        "YPA": "7.9",
        "PASS_TD": "16",
        "INT": "4",
        "SACKS": "18",
        "RUSH_ATT": "23",
        "RUSH_YDS": "33",
        "RUSH_TD": "2",
        "FUMBLES": "2",
        "GAMES_PLAYED": "11",
        "FPTS": "168.7",
        "FPTSPG": "15.3",
        "ROST": "29.9%"
    },
    {
        "RANK": "26",
        "NAME": "Matt Ryan (FA)",
        "CMP": "309",
        "PASS_ATT": "461",
        "PCT": "67.0",
        "PASS_YDS": "3,057",
        "YPA": "6.6",
        "PASS_TD": "14",
        "INT": "13",
        "SACKS": "38",
        "RUSH_ATT": "27",
        "RUSH_YDS": "70",
        "RUSH_TD": "1",
        "FUMBLES": "5",
        "GAMES_PLAYED": "12",
        "FPTS": "168.3",
        "FPTSPG": "14.0",
        "ROST": "6.1%"
    },
    {
        "RANK": "27",
        "NAME": "Ryan Tannehill (TEN)",
        "CMP": "212",
        "PASS_ATT": "325",
        "PCT": "65.2",
        "PASS_YDS": "2,536",
        "YPA": "7.8",
        "PASS_TD": "13",
        "INT": "6",
        "SACKS": "33",
        "RUSH_ATT": "34",
        "RUSH_YDS": "98",
        "RUSH_TD": "2",
        "FUMBLES": "2",
        "GAMES_PLAYED": "12",
        "FPTS": "167.2",
        "FPTSPG": "13.9",
        "ROST": "5.5%"
    },
    {
        "RANK": "28",
        "NAME": "Kenny Pickett (PIT)",
        "CMP": "245",
        "PASS_ATT": "389",
        "PCT": "63.0",
        "PASS_YDS": "2,404",
        "YPA": "6.2",
        "PASS_TD": "7",
        "INT": "9",
        "SACKS": "27",
        "RUSH_ATT": "55",
        "RUSH_YDS": "237",
        "RUSH_TD": "3",
        "FUMBLES": "1",
        "GAMES_PLAYED": "13",
        "FPTS": "159.0",
        "FPTSPG": "12.2",
        "ROST": "40.8%"
    },
    {
        "RANK": "29",
        "NAME": "Baker Mayfield (TB)",
        "CMP": "201",
        "PASS_ATT": "335",
        "PCT": "60.0",
        "PASS_YDS": "2,163",
        "YPA": "6.5",
        "PASS_TD": "10",
        "INT": "8",
        "SACKS": "36",
        "RUSH_ATT": "31",
        "RUSH_YDS": "89",
        "RUSH_TD": "1",
        "FUMBLES": "2",
        "GAMES_PLAYED": "12",
        "FPTS": "129.4",
        "FPTSPG": "10.8",
        "ROST": "3.8%"
    },
    {
        "RANK": "30",
        "NAME": "Taylor Heinicke (ATL)",
        "CMP": "161",
        "PASS_ATT": "259",
        "PCT": "62.2",
        "PASS_YDS": "1,859",
        "YPA": "7.2",
        "PASS_TD": "12",
        "INT": "6",
        "SACKS": "19",
        "RUSH_ATT": "28",
        "RUSH_YDS": "96",
        "RUSH_TD": "1",
        "FUMBLES": "5",
        "GAMES_PLAYED": "9",
        "FPTS": "121.9",
        "FPTSPG": "13.5",
        "ROST": "0.7%"
    },
    {
        "RANK": "31",
        "NAME": "Carson Wentz (FA)",
        "CMP": "172",
        "PASS_ATT": "276",
        "PCT": "62.3",
        "PASS_YDS": "1,755",
        "YPA": "6.4",
        "PASS_TD": "11",
        "INT": "9",
        "SACKS": "26",
        "RUSH_ATT": "22",
        "RUSH_YDS": "86",
        "RUSH_TD": "1",
        "FUMBLES": "1",
        "GAMES_PLAYED": "8",
        "FPTS": "121.8",
        "FPTSPG": "15.2",
        "ROST": "4.7%"
    },
    {
        "RANK": "32",
        "NAME": "Matthew Stafford (LAR)",
        "CMP": "206",
        "PASS_ATT": "303",
        "PCT": "68.0",
        "PASS_YDS": "2,087",
        "YPA": "6.9",
        "PASS_TD": "10",
        "INT": "8",
        "SACKS": "29",
        "RUSH_ATT": "13",
        "RUSH_YDS": "9",
        "RUSH_TD": "1",
        "FUMBLES": "3",
        "GAMES_PLAYED": "9",
        "FPTS": "116.5",
        "FPTSPG": "12.9",
        "ROST": "63.6%"
    },
    {
        "RANK": "33",
        "NAME": "Brock Purdy (SF)",
        "CMP": "114",
        "PASS_ATT": "170",
        "PCT": "67.1",
        "PASS_YDS": "1,374",
        "YPA": "8.1",
        "PASS_TD": "13",
        "INT": "4",
        "SACKS": "11",
        "RUSH_ATT": "22",
        "RUSH_YDS": "13",
        "RUSH_TD": "1",
        "FUMBLES": "0",
        "GAMES_PLAYED": "9",
        "FPTS": "110.3",
        "FPTSPG": "12.3",
        "ROST": "17.5%"
    },
    {
        "RANK": "34",
        "NAME": "Zach Wilson (NYJ)",
        "CMP": "132",
        "PASS_ATT": "242",
        "PCT": "54.5",
        "PASS_YDS": "1,688",
        "YPA": "7.0",
        "PASS_TD": "6",
        "INT": "7",
        "SACKS": "23",
        "RUSH_ATT": "28",
        "RUSH_YDS": "102",
        "RUSH_TD": "1",
        "FUMBLES": "1",
        "GAMES_PLAYED": "9",
        "FPTS": "106.0",
        "FPTSPG": "11.8",
        "ROST": "1.0%"
    },
    {
        "RANK": "35",
        "NAME": "Deshaun Watson (CLE)",
        "CMP": "99",
        "PASS_ATT": "170",
        "PCT": "58.2",
        "PASS_YDS": "1,102",
        "YPA": "6.5",
        "PASS_TD": "7",
        "INT": "5",
        "SACKS": "20",
        "RUSH_ATT": "36",
        "RUSH_YDS": "175",
        "RUSH_TD": "1",
        "FUMBLES": "0",
        "GAMES_PLAYED": "6",
        "FPTS": "90.5",
        "FPTSPG": "15.1",
        "ROST": "93.0%"
    },
    {
        "RANK": "36",
        "NAME": "Sam Darnold (SF)",
        "CMP": "82",
        "PASS_ATT": "140",
        "PCT": "58.6",
        "PASS_YDS": "1,143",
        "YPA": "8.2",
        "PASS_TD": "7",
        "INT": "3",
        "SACKS": "10",
        "RUSH_ATT": "26",
        "RUSH_YDS": "106",
        "RUSH_TD": "2",
        "FUMBLES": "2",
        "GAMES_PLAYED": "6",
        "FPTS": "89.3",
        "FPTSPG": "14.9",
        "ROST": "0.9%"
    },
    {
        "RANK": "37",
        "NAME": "Mitch Trubisky (PIT)",
        "CMP": "117",
        "PASS_ATT": "180",
        "PCT": "65.0",
        "PASS_YDS": "1,252",
        "YPA": "7.0",
        "PASS_TD": "4",
        "INT": "5",
        "SACKS": "11",
        "RUSH_ATT": "19",
        "RUSH_YDS": "38",
        "RUSH_TD": "2",
        "FUMBLES": "0",
        "GAMES_PLAYED": "7",
        "FPTS": "79.0",
        "FPTSPG": "11.3",
        "ROST": "0.3%"
    },
    {
        "RANK": "38",
        "NAME": "Mike White (MIA)",
        "CMP": "103",
        "PASS_ATT": "175",
        "PCT": "58.9",
        "PASS_YDS": "1,192",
        "YPA": "6.8",
        "PASS_TD": "3",
        "INT": "4",
        "SACKS": "9",
        "RUSH_ATT": "6",
        "RUSH_YDS": "9",
        "RUSH_TD": "1",
        "FUMBLES": "1",
        "GAMES_PLAYED": "4",
        "FPTS": "60.6",
        "FPTSPG": "15.2",
        "ROST": "0.9%"
    },
    {
        "RANK": "39",
        "NAME": "Cooper Rush (DAL)",
        "CMP": "94",
        "PASS_ATT": "162",
        "PCT": "58.0",
        "PASS_YDS": "1,051",
        "YPA": "6.5",
        "PASS_TD": "5",
        "INT": "3",
        "SACKS": "7",
        "RUSH_ATT": "9",
        "RUSH_YDS": "6",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "8",
        "FPTS": "59.6",
        "FPTSPG": "7.5",
        "ROST": "0.7%"
    },
    {
        "RANK": "40",
        "NAME": "Tyler Huntley (BAL)",
        "CMP": "75",
        "PASS_ATT": "112",
        "PCT": "67.0",
        "PASS_YDS": "658",
        "YPA": "5.9",
        "PASS_TD": "2",
        "INT": "3",
        "SACKS": "7",
        "RUSH_ATT": "43",
        "RUSH_YDS": "137",
        "RUSH_TD": "1",
        "FUMBLES": "0",
        "GAMES_PLAYED": "5",
        "FPTS": "53.0",
        "FPTSPG": "10.6",
        "ROST": "0.9%"
    },
    {
        "RANK": "41",
        "NAME": "Joe Flacco (FA)",
        "CMP": "110",
        "PASS_ATT": "191",
        "PCT": "57.6",
        "PASS_YDS": "1,051",
        "YPA": "5.5",
        "PASS_TD": "5",
        "INT": "3",
        "SACKS": "10",
        "RUSH_ATT": "3",
        "RUSH_YDS": "6",
        "RUSH_TD": "0",
        "FUMBLES": "4",
        "GAMES_PLAYED": "5",
        "FPTS": "51.4",
        "FPTSPG": "10.3",
        "ROST": "0.6%"
    },
    {
        "RANK": "42",
        "NAME": "Jameis Winston (NO)",
        "CMP": "73",
        "PASS_ATT": "115",
        "PCT": "63.5",
        "PASS_YDS": "858",
        "YPA": "7.5",
        "PASS_TD": "4",
        "INT": "5",
        "SACKS": "11",
        "RUSH_ATT": "5",
        "RUSH_YDS": "16",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "3",
        "FPTS": "48.9",
        "FPTSPG": "16.3",
        "ROST": "0.4%"
    },
    {
        "RANK": "43",
        "NAME": "Jarrett Stidham (DEN)",
        "CMP": "53",
        "PASS_ATT": "83",
        "PCT": "63.9",
        "PASS_YDS": "656",
        "YPA": "7.9",
        "PASS_TD": "4",
        "INT": "3",
        "SACKS": "7",
        "RUSH_ATT": "14",
        "RUSH_YDS": "84",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "3",
        "FPTS": "45.7",
        "FPTSPG": "15.2",
        "ROST": "0.6%"
    },
    {
        "RANK": "44",
        "NAME": "Bailey Zappe (NE)",
        "CMP": "65",
        "PASS_ATT": "92",
        "PCT": "70.7",
        "PASS_YDS": "781",
        "YPA": "8.5",
        "PASS_TD": "5",
        "INT": "3",
        "SACKS": "6",
        "RUSH_ATT": "10",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "3",
        "GAMES_PLAYED": "4",
        "FPTS": "42.7",
        "FPTSPG": "10.7",
        "ROST": "0.9%"
    },
    {
        "RANK": "45",
        "NAME": "P.J. Walker (CHI)",
        "CMP": "63",
        "PASS_ATT": "106",
        "PCT": "59.4",
        "PASS_YDS": "731",
        "YPA": "6.9",
        "PASS_TD": "3",
        "INT": "3",
        "SACKS": "7",
        "RUSH_ATT": "6",
        "RUSH_YDS": "39",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "6",
        "FPTS": "42.2",
        "FPTSPG": "7.0",
        "ROST": "0.7%"
    },
    {
        "RANK": "46",
        "NAME": "Teddy Bridgewater (FA)",
        "CMP": "49",
        "PASS_ATT": "79",
        "PCT": "62.0",
        "PASS_YDS": "683",
        "YPA": "8.6",
        "PASS_TD": "4",
        "INT": "4",
        "SACKS": "7",
        "RUSH_ATT": "3",
        "RUSH_YDS": "27",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "5",
        "FPTS": "42.0",
        "FPTSPG": "8.4",
        "ROST": "2.6%"
    },
    {
        "RANK": "47",
        "NAME": "Gardner Minshew II (IND)",
        "CMP": "44",
        "PASS_ATT": "76",
        "PCT": "57.9",
        "PASS_YDS": "663",
        "YPA": "8.7",
        "PASS_TD": "3",
        "INT": "3",
        "SACKS": "6",
        "RUSH_ATT": "7",
        "RUSH_YDS": "3",
        "RUSH_TD": "1",
        "FUMBLES": "1",
        "GAMES_PLAYED": "5",
        "FPTS": "39.8",
        "FPTSPG": "8.0",
        "ROST": "0.9%"
    },
    {
        "RANK": "48",
        "NAME": "Desmond Ridder (ATL)",
        "CMP": "73",
        "PASS_ATT": "115",
        "PCT": "63.5",
        "PASS_YDS": "708",
        "YPA": "6.2",
        "PASS_TD": "2",
        "INT": "0",
        "SACKS": "9",
        "RUSH_ATT": "16",
        "RUSH_YDS": "64",
        "RUSH_TD": "0",
        "FUMBLES": "2",
        "GAMES_PLAYED": "4",
        "FPTS": "38.8",
        "FPTSPG": "9.7",
        "ROST": "5.2%"
    },
    {
        "RANK": "49",
        "NAME": "Sam Ehlinger (IND)",
        "CMP": "64",
        "PASS_ATT": "101",
        "PCT": "63.4",
        "PASS_YDS": "573",
        "YPA": "5.7",
        "PASS_TD": "3",
        "INT": "3",
        "SACKS": "14",
        "RUSH_ATT": "17",
        "RUSH_YDS": "87",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "4",
        "FPTS": "38.6",
        "FPTSPG": "9.7",
        "ROST": "0.1%"
    },
    {
        "RANK": "50",
        "NAME": "Colt McCoy (ARI)",
        "CMP": "90",
        "PASS_ATT": "132",
        "PCT": "68.2",
        "PASS_YDS": "780",
        "YPA": "5.9",
        "PASS_TD": "1",
        "INT": "3",
        "SACKS": "13",
        "RUSH_ATT": "14",
        "RUSH_YDS": "36",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "4",
        "FPTS": "35.7",
        "FPTSPG": "8.9",
        "ROST": "0.7%"
    },
    {
        "RANK": "51",
        "NAME": "Joshua Dobbs (CLE)",
        "CMP": "40",
        "PASS_ATT": "68",
        "PCT": "58.8",
        "PASS_YDS": "411",
        "YPA": "6.0",
        "PASS_TD": "2",
        "INT": "2",
        "SACKS": "6",
        "RUSH_ATT": "8",
        "RUSH_YDS": "44",
        "RUSH_TD": "0",
        "FUMBLES": "2",
        "GAMES_PLAYED": "2",
        "FPTS": "22.9",
        "FPTSPG": "11.5",
        "ROST": "0.6%"
    },
    {
        "RANK": "52",
        "NAME": "Malik Willis (TEN)",
        "CMP": "31",
        "PASS_ATT": "61",
        "PCT": "50.8",
        "PASS_YDS": "276",
        "YPA": "4.5",
        "PASS_TD": "0",
        "INT": "3",
        "SACKS": "10",
        "RUSH_ATT": "27",
        "RUSH_YDS": "123",
        "RUSH_TD": "1",
        "FUMBLES": "2",
        "GAMES_PLAYED": "7",
        "FPTS": "22.3",
        "FPTSPG": "3.2",
        "ROST": "0.8%"
    },
    {
        "RANK": "53",
        "NAME": "Brett Rypien (LAR)",
        "CMP": "53",
        "PASS_ATT": "88",
        "PCT": "60.2",
        "PASS_YDS": "483",
        "YPA": "5.5",
        "PASS_TD": "2",
        "INT": "4",
        "SACKS": "8",
        "RUSH_ATT": "6",
        "RUSH_YDS": "7",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "4",
        "FPTS": "22.0",
        "FPTSPG": "5.5",
        "ROST": "0.1%"
    },
    {
        "RANK": "54",
        "NAME": "Davis Webb (FA)",
        "CMP": "23",
        "PASS_ATT": "40",
        "PCT": "57.5",
        "PASS_YDS": "168",
        "YPA": "4.2",
        "PASS_TD": "1",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "6",
        "RUSH_YDS": "41",
        "RUSH_TD": "1",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "20.8",
        "FPTSPG": "20.8",
        "ROST": "0.0%"
    },
    {
        "RANK": "55",
        "NAME": "David Blough (ARI)",
        "CMP": "38",
        "PASS_ATT": "58",
        "PCT": "65.5",
        "PASS_YDS": "402",
        "YPA": "6.9",
        "PASS_TD": "2",
        "INT": "2",
        "SACKS": "5",
        "RUSH_ATT": "4",
        "RUSH_YDS": "5",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "2",
        "FPTS": "20.6",
        "FPTSPG": "10.3",
        "ROST": "1.0%"
    },
    {
        "RANK": "56",
        "NAME": "Skylar Thompson (MIA)",
        "CMP": "60",
        "PASS_ATT": "105",
        "PCT": "57.1",
        "PASS_YDS": "534",
        "YPA": "5.1",
        "PASS_TD": "1",
        "INT": "3",
        "SACKS": "6",
        "RUSH_ATT": "14",
        "RUSH_YDS": "21",
        "RUSH_TD": "0",
        "FUMBLES": "2",
        "GAMES_PLAYED": "7",
        "FPTS": "20.5",
        "FPTSPG": "2.9",
        "ROST": "0.6%"
    },
    {
        "RANK": "57",
        "NAME": "Kyle Allen (BUF)",
        "CMP": "46",
        "PASS_ATT": "78",
        "PCT": "59.0",
        "PASS_YDS": "416",
        "YPA": "5.3",
        "PASS_TD": "2",
        "INT": "4",
        "SACKS": "5",
        "RUSH_ATT": "6",
        "RUSH_YDS": "13",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "3",
        "FPTS": "19.9",
        "FPTSPG": "6.6",
        "ROST": "0.2%"
    },
    {
        "RANK": "58",
        "NAME": "Sam Howell (WAS)",
        "CMP": "11",
        "PASS_ATT": "19",
        "PCT": "57.9",
        "PASS_YDS": "169",
        "YPA": "8.9",
        "PASS_TD": "1",
        "INT": "1",
        "SACKS": "3",
        "RUSH_ATT": "5",
        "RUSH_YDS": "35",
        "RUSH_TD": "1",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "19.3",
        "FPTSPG": "19.3",
        "ROST": "5.3%"
    },
    {
        "RANK": "59",
        "NAME": "John Wolford (TB)",
        "CMP": "38",
        "PASS_ATT": "62",
        "PCT": "61.3",
        "PASS_YDS": "390",
        "YPA": "6.3",
        "PASS_TD": "1",
        "INT": "3",
        "SACKS": "7",
        "RUSH_ATT": "8",
        "RUSH_YDS": "32",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "2",
        "FPTS": "17.8",
        "FPTSPG": "8.9",
        "ROST": "0.6%"
    },
    {
        "RANK": "60",
        "NAME": "Bryce Perkins (FA)",
        "CMP": "19",
        "PASS_ATT": "34",
        "PCT": "55.9",
        "PASS_YDS": "161",
        "YPA": "4.7",
        "PASS_TD": "1",
        "INT": "2",
        "SACKS": "6",
        "RUSH_ATT": "19",
        "RUSH_YDS": "90",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "5",
        "FPTS": "17.5",
        "FPTSPG": "3.5",
        "ROST": "0.6%"
    },
    {
        "RANK": "61",
        "NAME": "Jeff Driskel (ARI)",
        "CMP": "14",
        "PASS_ATT": "20",
        "PCT": "70.0",
        "PASS_YDS": "108",
        "YPA": "5.4",
        "PASS_TD": "1",
        "INT": "0",
        "SACKS": "2",
        "RUSH_ATT": "20",
        "RUSH_YDS": "75",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "7",
        "FPTS": "17.2",
        "FPTSPG": "2.5",
        "ROST": "1.0%"
    },
    {
        "RANK": "62",
        "NAME": "Trace McSorley (NE)",
        "CMP": "45",
        "PASS_ATT": "83",
        "PCT": "54.2",
        "PASS_YDS": "412",
        "YPA": "5.0",
        "PASS_TD": "0",
        "INT": "5",
        "SACKS": "3",
        "RUSH_ATT": "15",
        "RUSH_YDS": "61",
        "RUSH_TD": "0",
        "FUMBLES": "2",
        "GAMES_PLAYED": "5",
        "FPTS": "13.7",
        "FPTSPG": "2.7",
        "ROST": "0.6%"
    },
    {
        "RANK": "63",
        "NAME": "Trey Lance (SF)",
        "CMP": "15",
        "PASS_ATT": "31",
        "PCT": "48.4",
        "PASS_YDS": "194",
        "YPA": "6.3",
        "PASS_TD": "0",
        "INT": "1",
        "SACKS": "2",
        "RUSH_ATT": "16",
        "RUSH_YDS": "67",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "3",
        "FPTS": "13.5",
        "FPTSPG": "4.5",
        "ROST": "43.7%"
    },
    {
        "RANK": "64",
        "NAME": "Nick Mullens (MIN)",
        "CMP": "21",
        "PASS_ATT": "25",
        "PCT": "84.0",
        "PASS_YDS": "224",
        "YPA": "9.0",
        "PASS_TD": "1",
        "INT": "1",
        "SACKS": "0",
        "RUSH_ATT": "4",
        "RUSH_YDS": "8",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "4",
        "FPTS": "12.8",
        "FPTSPG": "3.2",
        "ROST": "0.6%"
    },
    {
        "RANK": "65",
        "NAME": "Tyrod Taylor (NYG)",
        "CMP": "6",
        "PASS_ATT": "8",
        "PCT": "75.0",
        "PASS_YDS": "58",
        "YPA": "7.3",
        "PASS_TD": "1",
        "INT": "1",
        "SACKS": "3",
        "RUSH_ATT": "5",
        "RUSH_YDS": "70",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "3",
        "FPTS": "12.3",
        "FPTSPG": "4.1",
        "ROST": "0.3%"
    },
    {
        "RANK": "66",
        "NAME": "Jordan Love (GB)",
        "CMP": "14",
        "PASS_ATT": "21",
        "PCT": "66.7",
        "PASS_YDS": "195",
        "YPA": "9.3",
        "PASS_TD": "1",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "1",
        "RUSH_YDS": "-1",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "4",
        "FPTS": "11.7",
        "FPTSPG": "2.9",
        "ROST": "49.4%"
    },
    {
        "RANK": "67",
        "NAME": "Trevor Siemian (CIN)",
        "CMP": "15",
        "PASS_ATT": "26",
        "PCT": "57.7",
        "PASS_YDS": "184",
        "YPA": "7.1",
        "PASS_TD": "1",
        "INT": "1",
        "SACKS": "2",
        "RUSH_ATT": "4",
        "RUSH_YDS": "8",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "2",
        "FPTS": "11.2",
        "FPTSPG": "5.6",
        "ROST": "0.1%"
    },
    {
        "RANK": "68",
        "NAME": "Nathan Peterman (CHI)",
        "CMP": "14",
        "PASS_ATT": "25",
        "PCT": "56.0",
        "PASS_YDS": "139",
        "YPA": "5.6",
        "PASS_TD": "1",
        "INT": "1",
        "SACKS": "1",
        "RUSH_ATT": "2",
        "RUSH_YDS": "7",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "3",
        "FPTS": "9.3",
        "FPTSPG": "3.1",
        "ROST": "0.6%"
    },
    {
        "RANK": "69",
        "NAME": "Chris Streveler (NYJ)",
        "CMP": "10",
        "PASS_ATT": "15",
        "PCT": "66.7",
        "PASS_YDS": "90",
        "YPA": "6.0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "9",
        "RUSH_YDS": "54",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "9.0",
        "FPTSPG": "9.0",
        "ROST": "0.6%"
    },
    {
        "RANK": "70",
        "NAME": "Chase Daniel (FA)",
        "CMP": "8",
        "PASS_ATT": "12",
        "PCT": "66.7",
        "PASS_YDS": "52",
        "YPA": "4.3",
        "PASS_TD": "1",
        "INT": "0",
        "SACKS": "1",
        "RUSH_ATT": "1",
        "RUSH_YDS": "4",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "3",
        "FPTS": "8.5",
        "FPTSPG": "2.8",
        "ROST": "0.0%"
    },
    {
        "RANK": "71",
        "NAME": "Anthony Brown (BAL)",
        "CMP": "22",
        "PASS_ATT": "49",
        "PCT": "44.9",
        "PASS_YDS": "302",
        "YPA": "6.2",
        "PASS_TD": "0",
        "INT": "2",
        "SACKS": "5",
        "RUSH_ATT": "3",
        "RUSH_YDS": "-5",
        "RUSH_TD": "0",
        "FUMBLES": "1",
        "GAMES_PLAYED": "2",
        "FPTS": "7.5",
        "FPTSPG": "3.8",
        "ROST": "0.1%"
    },
    {
        "RANK": "72",
        "NAME": "Nick Foles (FA)",
        "CMP": "25",
        "PASS_ATT": "42",
        "PCT": "59.5",
        "PASS_YDS": "224",
        "YPA": "5.3",
        "PASS_TD": "0",
        "INT": "4",
        "SACKS": "8",
        "RUSH_ATT": "2",
        "RUSH_YDS": "8",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "2",
        "FPTS": "5.7",
        "FPTSPG": "2.9",
        "ROST": "0.6%"
    },
    {
        "RANK": "73",
        "NAME": "Blaine Gabbert (KC)",
        "CMP": "6",
        "PASS_ATT": "8",
        "PCT": "75.0",
        "PASS_YDS": "29",
        "YPA": "3.6",
        "PASS_TD": "1",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "5.2",
        "FPTSPG": "5.2",
        "ROST": "0.6%"
    },
    {
        "RANK": "74",
        "NAME": "Brian Hoyer (LV)",
        "CMP": "5",
        "PASS_ATT": "6",
        "PCT": "83.3",
        "PASS_YDS": "37",
        "YPA": "6.2",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "1",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "1.5",
        "FPTSPG": "1.5",
        "ROST": "0.6%"
    },
    {
        "RANK": "75",
        "NAME": "Jacob Eason (FA)",
        "CMP": "3",
        "PASS_ATT": "5",
        "PCT": "60.0",
        "PASS_YDS": "59",
        "YPA": "11.8",
        "PASS_TD": "0",
        "INT": "1",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "1.4",
        "FPTSPG": "1.4",
        "ROST": "0.0%"
    },
    {
        "RANK": "76",
        "NAME": "Kyle Trask (TB)",
        "CMP": "3",
        "PASS_ATT": "9",
        "PCT": "33.3",
        "PASS_YDS": "23",
        "YPA": "2.6",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "0.9",
        "FPTSPG": "0.9",
        "ROST": "0.8%"
    },
    {
        "RANK": "77",
        "NAME": "Brandon Allen (SF)",
        "CMP": "3",
        "PASS_ATT": "3",
        "PCT": "100.0",
        "PASS_YDS": "22",
        "YPA": "7.3",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "1",
        "RUSH_ATT": "3",
        "RUSH_YDS": "-1",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "0.8",
        "FPTSPG": "0.8",
        "ROST": "0.6%"
    },
    {
        "RANK": "78",
        "NAME": "Josh Johnson (FA)",
        "CMP": "1",
        "PASS_ATT": "2",
        "PCT": "50.0",
        "PASS_YDS": "10",
        "YPA": "5.0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "2",
        "RUSH_YDS": "3",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "0.7",
        "FPTSPG": "0.7",
        "ROST": "0.0%"
    },
    {
        "RANK": "79",
        "NAME": "Case Keenum (HOU)",
        "CMP": "2",
        "PASS_ATT": "7",
        "PCT": "28.6",
        "PASS_YDS": "8",
        "YPA": "1.1",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "5",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "2",
        "FPTS": "0.3",
        "FPTSPG": "0.2",
        "ROST": "0.6%"
    },
    {
        "RANK": "80",
        "NAME": "Dresser Winn (LAR)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "81",
        "NAME": "Tommy DeVito (NYG)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "82",
        "NAME": "Nolan Henderson (BAL)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "83",
        "NAME": "James Blackman (MIA)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "84",
        "NAME": "Jake Fromm (WAS)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "85",
        "NAME": "Shane Buechele (KC)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "86",
        "NAME": "Kellen Mond (CLE)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.1%"
    },
    {
        "RANK": "87",
        "NAME": "Tim DeMorat (WAS)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "88",
        "NAME": "Ben DiNucci (DEN)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.1%"
    },
    {
        "RANK": "89",
        "NAME": "Ian Book (PHI)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "90",
        "NAME": "Dorian Thompson-Robinson (CLE)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "91",
        "NAME": "Cephus Johnson III (MIN)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "92",
        "NAME": "Sean Clifford (GB)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "93",
        "NAME": "Feleipe Franks (ATL)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "1",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "5",
        "FPTS": "0.0",
        "FPTSPG": "0.0",
        "ROST": "0.0%"
    },
    {
        "RANK": "94",
        "NAME": "Tanner Morgan (PIT)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "95",
        "NAME": "Stetson Bennett (LAR)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "96",
        "NAME": "Aidan O'Connell (LV)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "97",
        "NAME": "Jaren Hall (MIN)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "98",
        "NAME": "Hendon Hooker (DET)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "99",
        "NAME": "Jake Haener (NO)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.1%"
    },
    {
        "RANK": "100",
        "NAME": "Tanner McKee (PHI)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "101",
        "NAME": "Jarrett Guarantano (DEN)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "102",
        "NAME": "Davis Cheek (FA)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "0.0",
        "FPTSPG": "0.0",
        "ROST": "0.0%"
    },
    {
        "RANK": "103",
        "NAME": "Anthony Richardson (IND)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "69.7%"
    },
    {
        "RANK": "104",
        "NAME": "Chris Oladokun (KC)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "105",
        "NAME": "Chase Garbers (LV)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "106",
        "NAME": "Bryce Young (CAR)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "39.7%"
    },
    {
        "RANK": "107",
        "NAME": "Holton Ahlers (SEA)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "108",
        "NAME": "C.J. Stroud (HOU)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "18.3%"
    },
    {
        "RANK": "109",
        "NAME": "Max Duggan (LAC)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "110",
        "NAME": "Clayton Tune (ARI)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "111",
        "NAME": "Will Levis (TEN)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.3%"
    },
    {
        "RANK": "112",
        "NAME": "Malik Cunningham (NE)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "113",
        "NAME": "Nathan Rourke (JAC)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "114",
        "NAME": "Matt Corral (CAR)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "2",
        "FPTS": "0.0",
        "FPTSPG": "0.0",
        "ROST": "0.7%"
    },
    {
        "RANK": "115",
        "NAME": "Adrian Martinez (DET)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "116",
        "NAME": "Tyson Bagent (CHI)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "117",
        "NAME": "Ben Chappell (WAS)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "118",
        "NAME": "Adam Froman (ATL)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "119",
        "NAME": "Erik Ainge (NYJ)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "120",
        "NAME": "Hunter Cantwell (BAL)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "121",
        "NAME": "Keith Null (CAR)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "122",
        "NAME": "Brett Ratliff (TEN)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "123",
        "NAME": "Brian Brohm (BUF)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "124",
        "NAME": "Mason Rudolph (PIT)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.1%"
    },
    {
        "RANK": "125",
        "NAME": "Logan Woodside (ATL)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "0.0",
        "FPTSPG": "0.0",
        "ROST": "1.0%"
    },
    {
        "RANK": "126",
        "NAME": "C.J. Beathard (JAC)",
        "CMP": "7",
        "PASS_ATT": "11",
        "PCT": "63.6",
        "PASS_YDS": "35",
        "YPA": "3.2",
        "PASS_TD": "0",
        "INT": "1",
        "SACKS": "1",
        "RUSH_ATT": "4",
        "RUSH_YDS": "-4",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "4",
        "FPTS": "0.0",
        "FPTSPG": "0.0",
        "ROST": "0.6%"
    },
    {
        "RANK": "127",
        "NAME": "Easton Stick (LAC)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "128",
        "NAME": "Drew Lock (SEA)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.7%"
    },
    {
        "RANK": "129",
        "NAME": "Will Grier (DAL)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "130",
        "NAME": "Jake Browning (CIN)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "1.0%"
    },
    {
        "RANK": "131",
        "NAME": "John Lovett (MIA)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "132",
        "NAME": "Danny Etling (GB)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.6%"
    },
    {
        "RANK": "133",
        "NAME": "Austin Aune (ATL)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "134",
        "NAME": "Matt Barkley (BUF)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "0.0",
        "FPTSPG": "0.0",
        "ROST": "0.6%"
    },
    {
        "RANK": "135",
        "NAME": "Brett Smith (TB)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "0",
        "RUSH_YDS": "0",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "0",
        "FPTS": "0",
        "FPTSPG": "0",
        "ROST": "0.0%"
    },
    {
        "RANK": "136",
        "NAME": "Nate Sudfeld (DET)",
        "CMP": "0",
        "PASS_ATT": "0",
        "PCT": "0",
        "PASS_YDS": "0",
        "YPA": "0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "1",
        "RUSH_ATT": "5",
        "RUSH_YDS": "-4",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "2",
        "FPTS": "-0.4",
        "FPTSPG": "-0.2",
        "ROST": "0.6%"
    },
    {
        "RANK": "137",
        "NAME": "Chad Henne (FA)",
        "CMP": "0",
        "PASS_ATT": "2",
        "PCT": "0.0",
        "PASS_YDS": "0",
        "YPA": "0.0",
        "PASS_TD": "0",
        "INT": "0",
        "SACKS": "0",
        "RUSH_ATT": "5",
        "RUSH_YDS": "-5",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "3",
        "FPTS": "-0.5",
        "FPTSPG": "-0.2",
        "ROST": "0.1%"
    },
    {
        "RANK": "138",
        "NAME": "Tim Boyle (NYJ)",
        "CMP": "2",
        "PASS_ATT": "8",
        "PCT": "25.0",
        "PASS_YDS": "33",
        "YPA": "4.1",
        "PASS_TD": "0",
        "INT": "2",
        "SACKS": "0",
        "RUSH_ATT": "2",
        "RUSH_YDS": "-2",
        "RUSH_TD": "0",
        "FUMBLES": "0",
        "GAMES_PLAYED": "1",
        "FPTS": "-0.9",
        "FPTSPG": "-0.9",
        "ROST": "0.0%"
    }
]
